{"name": "Создание курьера с уже существующим логином", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('default_courier', <FixtureRequest for <Function test_courier_same_name>>)", "trace": "file D:\\Утилиты\\PythonProject\\PythonProject\\tests\\test_create_courier.py, line 16\n      @allure.title('Создание курьера с уже существующим логином')\n      @allure.description('Проверяем, что нельзя создать \"дубль\" существующего курьера. Ожидаем в ответ 409 и соответствующее письменное уведомление')\n      def test_courier_same_name(self, default_courier):\nE       fixture 'default_courier' not found\n>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, capteesys, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\Утилиты\\PythonProject\\PythonProject\\tests\\test_create_courier.py:16"}, "description": "Проверяем, что нельзя создать \"дубль\" существующего курьера. Ожидаем в ответ 409 и соответствующее письменное уведомление", "start": 1755447731601, "stop": 1755447731601, "uuid": "638f37af-8ecf-407b-98bc-d0a76df27810", "historyId": "420f8a23e312f2839951a287953a87cd", "testCaseId": "420f8a23e312f2839951a287953a87cd", "fullName": "tests.test_create_courier.TestCreateCourier#test_courier_same_name", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "Forcecom"}, {"name": "thread", "value": "3868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}], "titlePath": ["tests", "test_create_courier.py", "TestCreateCourier"]}